// <auto-generated />
using System;
using FeuerSoftware.TetraControl2Connect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeuerSoftware.TetraControl2Connect.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.AdditionalPatternEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatternSettingsId");

                    b.ToTable("AdditionalPatterns");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.FailureTranslationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SirenStatusSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SirenStatusSettingsId");

                    b.ToTable("FailureTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.PatternSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FactsPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumberPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LatitudePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongitudePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterNamePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterPhoneNumberPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RicPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCodePattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PatternSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.ProgramSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptCalloutsForSirens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptSDSAsCalloutsWithPattern")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AddPropertyForAlarmTexts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeartbeatEndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartbeatInterval")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreAlarmWithoutSubnetAddresses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreStatus0")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreStatus5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IgnoreStatus9")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PollForActiveOperationBeforeFallbackDelay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollForActiveOperationBeforeFallbackMaxRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendAlarms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendUserAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendUserOperationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendVehiclePositions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendVehicleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateExistingOperations")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseFullyQualifiedSubnetAddressForConnect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserAvailabilityLifetimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebSocketReconnectTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProgramSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SettingsBackupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingsBackups");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SeveritySettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseServerityTranslationAsKeyword")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SeveritySettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SeverityTranslationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeveritySettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeveritySettingsId");

                    b.ToTable("SeverityTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenCalloutSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSirenCodeTranslationAsKeyword")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SirenCalloutSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenCodeTranslationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SirenCalloutSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SirenCalloutSettingsId");

                    b.ToTable("SirenCodeTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedHeartbeatInterval")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Sirens");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenStatusSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SirenStatusSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.StatusSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComingLaterStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitedAvailableStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotAvailableStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotComingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SubnetAddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlarmDirectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GSSI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SNA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SubnetAddresses");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.TetraControlSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TetraControlHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TetraControlPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TetraControlPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TetraControlUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TetraControlSettings");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.AdditionalPatternEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.PatternSettingsEntity", null)
                        .WithMany("AdditionalProperties")
                        .HasForeignKey("PatternSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.FailureTranslationEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.SirenStatusSettingsEntity", null)
                        .WithMany("FailureTranslations")
                        .HasForeignKey("SirenStatusSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SeverityTranslationEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.SeveritySettingsEntity", null)
                        .WithMany("SeverityTranslations")
                        .HasForeignKey("SeveritySettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenCodeTranslationEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.SirenCalloutSettingsEntity", null)
                        .WithMany("SirenCodeTranslations")
                        .HasForeignKey("SirenCalloutSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.SiteEntity", null)
                        .WithMany("Sirens")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SubnetAddressEntity", b =>
                {
                    b.HasOne("FeuerSoftware.TetraControl2Connect.Data.SiteEntity", null)
                        .WithMany("SubnetAddresses")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.PatternSettingsEntity", b =>
                {
                    b.Navigation("AdditionalProperties");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SeveritySettingsEntity", b =>
                {
                    b.Navigation("SeverityTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenCalloutSettingsEntity", b =>
                {
                    b.Navigation("SirenCodeTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SirenStatusSettingsEntity", b =>
                {
                    b.Navigation("FailureTranslations");
                });

            modelBuilder.Entity("FeuerSoftware.TetraControl2Connect.Data.SiteEntity", b =>
                {
                    b.Navigation("Sirens");

                    b.Navigation("SubnetAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
